### PR TITLE
Add preset icons

### PR DESCRIPTION
**Pull request by savage13**

### CODE REVIEW

**Comment by Pistonight** [comment]
Can we pull assets directly from icons.pistonite.org and the objmap?

**Comment by savage13** [comment]
Many of the icons on the objmap are svg.

**Comment by Pistonight** [comment]
nvm then. We could still use icons.pistonite.org url for the shrine, tower and lightroot

**Comment by Pistonight** [comment]
Closing this as presets will be maintained in a different repo

**Pull request closed without merging**
